### ISSUE TITLE
FreeBSD r283276 adds new requirements for FDT building

### ISSUE THREAD

**Issue by f-andrey** [freebsd/crochet#113]
After https://svnweb.freebsd.org/base?view=revision&revision=283276 there may be problems with the build of some of the platforms that I encountered during build BEAGLEBONE.

Info for compilation error and recommendations @gonzoua
https://lists.freebsd.org/pipermail/freebsd-arm/2015-May/011486.html

**Comment by kientzle** [comment]
Copying Gonzo's comments here for reference:

> #include in dts file is handled by cpp(1). /include/ is handled
> by dtc I believe
>
> You can take a look at how FreeBSD compiles dts files in
> sys/tools/fdt/make_dtb.sh
>
> crochet does not have cpp stage of compilation and before my TI
> code/devicetree refactoring none of the dts files referenced in
> crochet used #include. That's why problem never appeared. 
>
> Fix is just a matter of fixing freebsd_install_fdt in lib/freebsd.sh.
> If nobody beats me to it I'll try to fix it and submit pull request to Tim.

**Comment by kientzle** [comment]
Should be fixed now.
