### ISSUE TITLE
error: "hw.ncpu" is an unknown key

### ISSUE THREAD

**Issue by thotheolh** [freebsd/crochet#130]
I tried to run crochet according to the "How to Build a Disk Image" page with crochet configured and a FreeBSD image ready on an Ubuntu machine.

I hit the following error:

thotheolh@thotheolh-Ultra:~/Desktop/RPi-FreeBSD/crochet$ sudo ./crochet.sh -c config.sh
Starting at Thu Oct 1 10:21:29 SGT 2015
error: "hw.ncpu" is an unknown key

In the config.sh, I copied it from the config.sh.sample and only did a single edit which is to uncomment the "board_setup RaspberryPi" since my target build is for a RaspberryPi Model B (Generation 1).

**Comment by brd** [comment]
FreeBSD cannot be built on linux due to other issues.. I'd recommend grabbing one of the Raspberry Pi images from the downloads page on FreeBSD.org.
