### ISSUE TITLE
Add Support for the Raspberry Pi 3

### ISSUE THREAD

**Issue by DatanoiseTV** [freebsd/crochet#144]
Please add ARMv8 64-bit HF support for crochet.

Differences to V2: http://raspberry.piaustralia.com.au/raspberry-pi-3-model-b-changes/

**Comment by mko-io** [comment]
please the Freebsd arm64 image is in alpha and available for download:

ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/aarch64/ISO-IMAGES/11.0//FreeBSD-11.0-ALPHA1-arm64-aarch64-20160528-r300895-memstick.img

**Comment by rascal-hats** [comment]
11.0 links are dead, new links here:

ftp://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/aarch64/ISO-IMAGES/12.0/

http://ftp.freebsd.org/pub/FreeBSD/snapshots/arm64/aarch64/ISO-IMAGES/12.0/

**Comment by catzilla4** [comment]
Sorry if I come off as a newbie, I'm interested in helping make the FreeBSD run on the Pi 3.  Unfortunately, I've been less than successful at it myself, so when I saw the initial commit I figured I should state this.

**Comment by brd** [comment]
It has been committed and I have uploaded images to http://www.raspbsd.org.  There is still lots more work to be done.

**Comment by mko-io** [comment]
@brd that's awesome. Do you have upload a image for Pine64?

**Comment by brd** [comment]
@mko-io Uploaded to http://www.raspbsd.org/pine64.html !
