### ISSUE TITLE
cubieboard3

### ISSUE THREAD

**Issue by baos780** [freebsd/crochet#145]
Any chance of support for cubietruck?   I was able to make it boot with the cubieboard2 image.  That was about all it did.  cubieboard3/cubietruck as far as I know is the only one with sata not tied to usb speeds.  
http://www.cubietruck.com/collections/frontpage/products/cubietruck-cubieboard3-cortex-a7-dual-core-2gb-ram-8gb-flash-with-wifi-bt-1

**Comment by kientzle** [comment]
The freebsd-arm mailing list is a much better place to ask about FreeBSD support for new boards.

  https://www.freebsd.org/community/mailinglists.html
