### ISSUE TITLE
Add Support for the Orange Pi (Allwiner H3)

### ISSUE THREAD

**Issue by Trapizomba** [freebsd/crochet#157]
Cheaper and more powerful than Raspberry Pi...
More info: http://www.orangepi.org/

**Comment by evadot** [comment]
We have to wait for the Linux 4.7 DTS import for this.
Otherwise the board is already supported and a I've created a u-boot port : https://github.com/freebsd/freebsd-ports/tree/master/sysutils/u-boot-orangepi-one

**Comment by vgrebenschikov** [comment]
Added pull-request for OrangePi Plus2E, other should be similar, u-boot port also required (see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=214729)

**Comment by kientzle** [comment]
Looks like this is done now?
