### ISSUE TITLE
fatal error for Pine64+

### ISSUE THREAD

**Issue by zhaojie1130** [freebsd/crochet#175]
Hi,

I'm trying to build FreeBSD11-Stable for Pine64+ and encountered the following error: 

<built-in>:329:10: fatal error: '/usr/src/sys/boot/fdt/dts/arm64/pine64_plus.dts' file not found

Checked https://wiki.freebsd.org/FreeBSD/arm/Allwinner
and it says the Allwinner A64 CPU has been supported since r305134
Tried to google the missing file but found no result.

My Build Env:
Working Copy Root Path: /usr/src
URL: https://svn.freebsd.org/base/stable/11
Revision: 312658
Schedule: normal
Last Changed Author: pfg
Last Changed Rev: 312656
Last Changed Date: 2017-01-23 12:20:58 +1100 (Mon, 23 Jan 2017)

**Comment by brd** [comment]
FreeBSD 11 does not support the Pine64.  You'll need to use 12.

You can also just download a prebuilt image from here: http://www.raspbsd.org/pine64.html
