### ISSUE TITLE
dd: /dev/md4: Invalid argument on u-boot installation for banana-pi

### ISSUE THREAD

**Issue by MoritzFago** [freebsd/crochet#191]
During the image creation process the setup.sh burns the various boot loader files to the image.
```csh
Installing U-Boot files
+ dd if=/usr/local/share/u-boot/u-boot-bananapi/sunxi-spl.bin of=/dev/md4 bs=1024 seek=8
dd: /dev/md4: Invalid argument
486+1 records in
486+0 records out
497664 bytes transferred in 5.784579 secs (86033 bytes/sec)
```
I am building in a jail with the following flags `allow.mount=true,enforce_statfs=1`

**Comment by fjerhammer** [comment]
This is also happening for me. 11.0-STABLE, not using jails.

**Comment by arrowd** [comment]
And me too.

**Comment by alexey1234** [comment]
And me too

**Comment by swilde** [comment]
Here too.

**Comment by arrowd** [comment]
So, is crochet completely unusable right now? The offending line is https://github.com/freebsd/crochet/blob/master/lib/disk.sh#L47 but I don't know what to do with it.

**Comment by arrowd** [comment]
Ah, no, that line has nothing to do with the problem.

**Comment by kientzle** [comment]
To debug this, you can (temporarily) edit `board/BananaPi/setup.sh` to print out more information at the top of the `allwinner_partition_image()` function.  In particular, it would probably make sense to try `ls -l /dev/${DISK_MD}` to make sure the md device was created, and maybe `mdconfig -l` to list all the existing md devices.

**Comment by kientzle** [comment]
@loos-br might be right.  If /usr/local/share/u-boot/u-boot-bananapi/sunxi-spl.bin is not a multiple of the block size, then adding `conv=sync` to the `dd` command originally mentioned may fix it.

**Comment by kientzle** [comment]
I believe #199 fixes this; please try and let us know.
