### ISSUE TITLE
bananapi write failed, filesystem is full

### ISSUE THREAD

**Issue by ric96** [freebsd/crochet#204]
while building default image for bananapi using
```
$ sudo /bin/sh crochet.sh -b BananaPi
```
After compilation the image file created is too small, easiest solution is to edit the board/BananaPi/setup.sh file. some like this i did to get 7gb image, although 2gb should be enough.
```
IMAGE_SIZE=$((1000 * 1000 * 1000 * 7))
```

**Comment by kientzle** [comment]
Is 1900MB sufficient?  (That would fit onto common "2GB" media.)
```
IMAGE_SIZE=$((1000 * 1000 * 1900))
```
If you could test this for me, I can quickly make that change.

**Comment by ric96** [comment]
yup, works fine for me...

**Comment by kientzle** [comment]
Good.  I just pushed a commit changing the default to 1.9GB.

Thanks!
