### ISSUE TITLE
Include the board's name in the image's name

### ISSUE THREAD

**Issue by gczuczy** [freebsd/crochet#207]
Hello,

In case of multiple boards around, if would be quite useful to know which image corresponds to which board. And also, the same checkout/arch/kernconf not overwriting the image of another board is not the least to consider. And I think it would do good to the images at raspbsd.org as well.

Ho do you feel about it? If you also think this would be useful, I can submit a pull request for this.

Thanks,
-czg

**Comment by gczuczy** [comment]
Pull request for it: https://github.com/freebsd/crochet/pull/209

**Comment by gczuczy** [comment]
Oh, and the generated image names for the testrun:
```
-rw-r--r--   1 root  wheel   3.6G Aug 23 13:41 FreeBSD-aarch64-12.0-AEGIR-322723M-RaspberryPi3.img
-rw-r--r--   1 root  wheel   307M Aug 23 13:41 FreeBSD-aarch64-12.0-AEGIR-322723M-RaspberryPi3.img.gz
```

**Comment by kientzle** [comment]
Thanks
