### ISSUE TITLE
RaspberryPi2 board setup.sh sets KERNCONF=GENERIC, but GENERIC does not exist

### ISSUE THREAD

**Issue by sonologic** [freebsd/crochet#220]
Not sure if i'm doing something wrong, and this used to work before, but on my latest attempt to build an image for the rpi2, I got an error:

```Didn't find /usr/src/freebsd_rpi2b/crochet/src/sys/arm/conf/GENERIC```

And indeed this file does not exist in the releng/11.1 branch:

https://github.com/freebsd/freebsd/tree/releng/11.1/sys/arm/conf

I'm pretty sure that my previous image did build with the RPI2 config, given the output of uname when running that image:

```FreeBSD pi.localnet 11.1-RELEASE-p5 FreeBSD 11.1-RELEASE-p5 #0 r313908+d1ca5f865fb(releng/11.1): Fri Dec  1 22:16:28 CET 2017     gmc@enterprise:/usr/src/freebsd_rpi2b/crochet/work/obj/arm.armv6/usr/src/freebsd_rpi2b/crochet/src/sys/RPI2  arm```

I see the KERNCONF was changed in the board's setup.sh here:

https://github.com/freebsd/crochet/commit/cf14b342e312ba649dffa0ac4921118da8a1d214#diff-8ba6e6ecb3698ee1596ff547ed430cac

So I guess when i did a pull from origin before rebuilding, I pulled in that change and now the default setup is broken.

What I can't figure out is how this is supposed to work with a non-existing GENERIC kernel config. Of course, I can set KERNCONF=RPI2 in config.sh, but I would expect the default to use that instead of GENERIC.

**Comment by sonologic** [comment]
Hmm, that's not the only problem i'm getting it seems. Building now stops with another error:

```cd: stand: No such file or directory```

Is crochet supposed to work with 11.1 at all, or am I just trying some combination that I shouldn't?

**Comment by snail59** [comment]
Hello

I had the same problems as you.

1.  KERNCONF
Installing **gsed** corrected this issue.

2. stand
The commit 5222b4da9a7f38daffb84c46c132aa649dd721ae reads "**Reflect base r325834- sys/boot has relocated to stand**". \
But this r325834 commit is only present in  **head**, not in **freebsd 11.1**.
Waiting for a more " adapted" solution, reverting the commit did the trick for me :
` git revert 5222b4da9a7f38daffb84c46c132aa649dd721ae`

**Comment by brd** [comment]
Generally we target HEAD because that is what will support the boards the best.

Though handling this properly is probably a good idea for older boards.
