### ISSUE TITLE
no board directory for Orange Pi PC Plus and Orange Pi One

### ISSUE THREAD

**Issue by CurtisVillamizar** [freebsd/crochet#248]
Board directories are provided in https://github.com/freebsd/crochet/pull/245 and https://github.com/freebsd/crochet/pull/246 .  Both have been tested for 2 weeks to a month of light use including some port builds and testing.

**Comment by laytonwang** [comment]
Yes , board entry  is expected to list in config.sh.sample file eagerly.

**Comment by CurtisVillamizar** [comment]
Both pull requests have been picked up so this issue can be closed.
