### ISSUE TITLE
RPI4 support

### ISSUE THREAD

**Issue by Yzed** [freebsd/crochet#284]
what are we mainly missing for RPI4 support? u-boot?

**Comment by ykla** [comment]
I also want to learn about it. This project seems likes not updated long times.

**Comment by brd** [comment]
Most of the work happens in the FreeBSD trees, only small bits needed happen here.  Earlier there was some discussion on the FreeBSD-arm mailing list:

https://lists.freebsd.org/pipermail/freebsd-arm/2019-August/020285.html

Once u-boot, etc happen crochet can be updated.

**Comment by ykla** [comment]
long time...
