### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by enriquefynn** [freebsd/crochet#55]
I'm trying to create a raspberry pi new bootable, and faced with the following error using the default config.

Using U-Boot from previous build.
====================> Phase 301 <====================
Running:  OPTION= OPTIONDIR= BOARDDIR= board_default_create_image
eval: arithmetic expression: expecting primary: "\([0-9][0-9]*\).*$/\1/p'`-RPI-B-r263927.img / 1000000"

I hardcoded the name of the image, so it worked.

**Comment by kientzle** [comment]
I've not heard any other reports, so I suspect this was fixed at some point.

If you see it again, please open another issue and I'll take another look.
