### ISSUE TITLE
Renaming "strategy"

### ISSUE THREAD

**Issue by xoro** [freebsd/crochet#81]
As the comment in strategy.sh shows:
    # TODO: Rename 'strategy' to something more appropriate, since
    # this has nothing to do with the 'strategy pattern.'  That
    # will involve renaming this file and a lot of internal variables
    # and functions...
My proposal would be to rename strategy to sequencer and a phase of the strategy would be a sequence!?
I would offer to rename everything if all agree!

**Comment by kientzle** [comment]
Closing.
