### ISSUE TITLE
Use ubuntu to build????

### ISSUE THREAD

**Issue by ric96** [freebsd/crochet#92]
Can I use ubuntu to build images?? 
When ever i try i always end up with this error :

ric@ric-ubuntu:~/crochet-freebsd$ sudo ./crochet.sh -b RaspberryPi
Starting at Mon Oct 13 09:07:43 IST 2014
Board: RaspberryPi
Source version is: unknown
./crochet.sh: 1: ./crochet.sh: /usr/bin/grep: not found
Building FreeBSD version: 
Image name is:
    /home/ric/crochet-freebsd/work/FreeBSD-armv6--RPI-B.img
Can't find appropriate FreeBSD xdev tools.
Tested: armv6-freebsd-cc
If you have FreeBSD-CURRENT sources in /usr/src, you can build these with the following command:

cd /usr/src && sudo make XDEV=arm XDEV_ARCH=armv6 WITH_GCC=1 WITH_GCC_BOOTSTRAP=1 WITHOUT_CLANG=1 WITHOUT_CLANG_BOOTSTRAP=1 WITHOUT_CLANG_IS_CC=1 xdev

Run this script again after you have the xdev tools installed.
ric@ric-ubuntu:~/crochet-freebsd$

**Comment by elielmathe** [comment]
This is also my question.
I have downloaded the freebsd source code, now I want to create a disk image from it. How can I do it?

**Comment by kientzle** [comment]
Instructions:  https://github.com/freebsd/crochet/wiki/How-to-Build-a-Disk-Image

**Comment by blacknes** [comment]
try on FreeBSD 9-STABLE.

**Comment by brd** [comment]
@blacknes Please do not recommend such an old version on FreeBSD. 10.2 or HEAD would be best.
